group 'com.originoss.flutter_html_to_pdf_plus'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.9.24'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        if (project.findProperty('android.builtInKotlin') != 'true') {
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        }
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

if (project.findProperty('android.builtInKotlin') != 'true') {
    apply plugin: 'kotlin-android'
}

android {
    namespace 'com.originoss.flutter_html_to_pdf_plus'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 19
    }
}

dependencies {
    if (project.findProperty('android.builtInKotlin') != 'true') {
        implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    }
}
